### ISSUE TITLE
demo server hangs

### ISSUE THREAD

**Issue by kewp** [mrohad/Alligator#1]
hi there.

i like the look of your framework. very interesting.

i'm testing out the demo in the repository. when i run it and try connect from a browser it the browser hangs, just keeps loading.

i'm on the latest ubuntu. i'm running it locally. i've tried firefox and chrome. same on both. i've also tried running it from my vps. same thing. in the console logs everything seems fine. it recognises the connection request. seems to log everything fine. but the browsers just keep loading, displaying nothing. eventually firefox did display hello world, but i couldn't replicate it.

i haven't changed the settings.json, except to set the home path. i've also tried other ports, and increasing the session time.

hope that helps.

**Comment by mrohad** [comment]
sorry for the late reply,
I fixed that issue, can you give it a retry?

**Comment by kewp** [comment]
hey.

still seems like the same issue.
this is a dump of the session i've just tried.

karl@ve:~/fiddle$ git clone https://github.com/mrohad/Alligator.git
Initialized empty Git repository in /home/karl/fiddle/Alligator/.git/
remote: Counting objects: 227, done.
remote: Compressing objects: 100% (215/215), done.
remote: Total 227 (delta 121), reused 0 (delta 0)
Receiving objects: 100% (227/227), 277.50 KiB, done.
Resolving deltas: 100% (121/121), done.
karl@ve:~/fiddle$ cd Alligator/
karl@ve:~/fiddle/Alligator$ ls
AlligatorV035.tar.gz  AlligatorV037.tar.gz  ChangeLog  LICENSE  README.markdown  WWW  WWWlib  alligator.js  futureFeatures.txt  knowBugs.txt  lib  package.json  settings.json
karl@ve:~/fiddle/Alligator$ nano settings.json
karl@ve:~/fiddle/Alligator$ sudo node alligator.js
13/02/11 14:2M:55[DEBUG] Engine : S E T   L O G   l e v e l   t o   -   D E B U G
13/02/11 14:2M:55[DEBUG] Page : S E T   L O G   l e v e l   t o   -   D E B U G
13/02/11 14:2M:55[INFO] Engine : Starting Web App - Alligator TestApp
13/02/11 14:2M:55[WARN] Engine : Server running at port 82
13/02/11 14:2M:55[INFO] Engine : Loading lib file:/home/karl/fiddle/Alligator/WWWlib/test
13/02/11 14:2M:00[DEBUG] Engine : request arrived!
13/02/11 14:2M:00[INFO] Engine : Handling request to: /home/karl/fiddle/Alligator/WWW/ pid(14296)
13/02/11 14:2M:00[INFO] Engine : Static request
13/02/11 14:2M:00[INFO] Engine : 197.170.63.168 GET 200 4096

same thing - when i hit my domain on port 82 the browser just shows loading with no result....

**Comment by mrohad** [comment]
Which JSSP page are you trying to get?

**Comment by kewp** [comment]
what is a jssp??

**Comment by mrohad** [comment]
try the readme.
Alligator is a web-server that works a bit like tomcat
you can develop JSSP pages and SSJS code , you put those pages in the WWW folder and then you execute those pages as following
http://server:port/pageName.jssp

**Comment by kewp** [comment]
hmmm. ok, i see.

i hit sample.jssp and it seems to work fine.

it's loading index.html that hangs... ?

**Comment by mrohad** [comment]
it works great for me
Do you see anything on the console?
it should say that it serves a static page..
